# Generated by Django 3.2.7 on 2021-09-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
    ]
