# Generated by Django 3.2.7 on 2021-09-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_alter_country_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='short_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='gmap',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
