# Generated by Django 3.2.7 on 2021-09-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='url',
            new_name='urls',
        ),
        migrations.AddField(
            model_name='researcher',
            name='name',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='researcher',
            name='tags',
            field=models.JSONField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='localization.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='university',
            name='tags',
            field=models.JSONField(default=None, max_length=400),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=400)),
                ('url', models.CharField(default=None, max_length=200)),
                ('tags', models.JSONField(default=None, max_length=400)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.university')),
            ],
        ),
        migrations.AddField(
            model_name='researcher',
            name='articles',
            field=models.ManyToManyField(to='main.Article'),
        ),
    ]
