# Generated by Django 3.2.7 on 2021-09-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210924_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='university',
        ),
        migrations.AddField(
            model_name='researcher',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='main.university'),
            preserve_default=False,
        ),
    ]
