# Generated by Django 3.2.7 on 2021-09-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210924_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='hindex',
            field=models.IntegerField(default=0),
        ),
    ]
