# Generated by Django 3.2.7 on 2021-09-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_alter_country_short_name'),
        ('main', '0006_auto_20210926_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='localization.location'),
        ),
    ]
