# Generated by Django 3.2.7 on 2021-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_university_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='hindex',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
