# Generated by Django 3.2.7 on 2021-09-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_researcher_hindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='email',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='role',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
