# Generated by Django 3.2.7 on 2021-10-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_researcher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='tags',
            field=models.JSONField(max_length=800, null=True),
        ),
    ]
