# Generated by Django 3.2.7 on 2021-10-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211001_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='researcher',
            name='interests',
            field=models.TextField(null=True),
        ),
    ]
