# Generated by Django 3.2.7 on 2021-10-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211001_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='fields',
            field=models.JSONField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='hindex',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='urls',
            field=models.JSONField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
