# Generated by Django 3.2.7 on 2021-10-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211001_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=models.CharField(default='hi', max_length=250),
            preserve_default=False,
        ),
    ]
