# Generated by Django 3.2.7 on 2021-10-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_researcher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fields',
            field=models.JSONField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='relatedPeople',
            field=models.JSONField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='fields',
            field=models.JSONField(max_length=500, null=True),
        ),
    ]
