# Generated by Django 3.2.7 on 2021-10-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211002_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='contactInfo',
            field=models.TextField(null=True),
        ),
    ]
