# Generated by Django 3.2.7 on 2021-10-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_researcher_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='role',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
