# Generated by Django 3.2.7 on 2021-10-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_researcher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='color',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.TextField(null=True),
        ),
    ]
