# Generated by Django 3.2.7 on 2021-11-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211003_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=models.CharField(default='<Requires Update>', max_length=250),
        ),
    ]
