FROM ubuntu:20.04
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN sh -c echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list
RUN apt-get update
RUN apt-get install -y curl gnupg
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update
RUN apt-get install -y cmake build-essential python3-pip python3
RUN apt-get install ros-noetic-ros-base
RUN pip3 install -U catkin_tools
WORKDIR catkin_ws
RUN catkin_make
WORKDIR src
RUN catkin_init_workspace
WORKDIR ../build
RUN cmake ../src -DCMAKE_INSTALL_PREFIX=../install -DCATKIN_DEVEL_PREFIX=../devel
RUN catkin_make
WORKDIR ../..
ENTRYPOINT ["catkin_ws/devel/setup.bash"]